import { InspectionRequestDataType } from "./InspectionRequestDataType";

// export const inspectionRequests: InspectionRequestDataType[] = [
//   {
//     requestId: "#10109089",
//     fullname: "Gbenga Sonoiki",
//     email: "reginaldabiepepple@gmail.com",
//     propertyAddress: "14 Adamawa Street",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 916 0140 422",
//     landlordAgentNumber: "+234 988 746 667",
//     propertyType: "Duplex",
//     linkToProperty: "www.tivro.africca",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Reginald Pepple",
//   },
//   {
//     requestId: "#10109090",
//     name: "Aisha Bello",
//     email: "aisha.bello@gmail.com",
//     propertyAddress: "22 Kano Crescent",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 812 345 6789",
//     landlordAgentNumber: "+234 909 876 5432",
//     propertyType: "Apartment",
//     linkToProperty: "www.homes.ng/kano-apartment",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Aisha Bello",
//   },
//   {
//     requestId: "#10109091",
//     name: "Emeka Okafor",
//     email: "emeka.okafor@yahoo.com",
//     propertyAddress: "7 Enugu Road",
//     assignedAgent: "Assigned",
//     status: "Failed",
//     phoneNumber: "+234 803 123 4567",
//     landlordAgentNumber: "+234 701 234 5678",
//     propertyType: "Bungalow",
//     linkToProperty: "www.propertyhub.com/enugu-bungalow",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Emeka Okafor",
//   },
//   {
//     requestId: "#10109092",
//     name: "Chioma Umeh",
//     email: "chioma.umeh@outlook.com",
//     propertyAddress: "5 Owerri Lane",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 805 678 9123",
//     landlordAgentNumber: "+234 902 345 6789",
//     propertyType: "Duplex",
//     linkToProperty: "www.tivro.africca/owerri",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Chioma Umeh",
//   },
//   {
//     requestId: "#10109093",
//     name: "David Mark",
//     email: "david.mark@gmail.com",
//     propertyAddress: "10 Abuja Drive",
//     assignedAgent: "James John",
//     status: "Completed",
//     phoneNumber: "+234 818 234 5678",
//     landlordAgentNumber: "+234 803 345 6780",
//     propertyType: "Studio",
//     linkToProperty: "www.rentnaija.com/abuja-studio",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "David Mark",
//   },
//   {
//     requestId: "#10109094",
//     name: "Tolu Ajayi",
//     email: "tolu.ajayi@live.com",
//     propertyAddress: "3 Lekki Phase 1",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 816 789 0123",
//     landlordAgentNumber: "+234 705 654 3210",
//     propertyType: "Penthouse",
//     linkToProperty: "www.nigeriaproperties.com/lekki",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Tolu Ajayi",
//   },
//   {
//     requestId: "#10109095",
//     name: "Rita Eze",
//     email: "rita.eze@yahoo.com",
//     propertyAddress: "16 Port Harcourt Street",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 814 234 9087",
//     landlordAgentNumber: "+234 708 321 4567",
//     propertyType: "Flat",
//     linkToProperty: "www.tivro.africca/ph-flat",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Rita Eze",
//   },
//   {
//     requestId: "#10109096",
//     name: "Yusuf Ibrahim",
//     email: "yusuf.ibrahim@gmail.com",
//     propertyAddress: "45 Zaria Road",
//     assignedAgent: "Amina Bello",
//     status: "Failed",
//     phoneNumber: "+234 809 876 1234",
//     landlordAgentNumber: "+234 806 543 2198",
//     propertyType: "Terrace",
//     linkToProperty: "www.naijahomes.com/zaria",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Yusuf Ibrahim",
//   },
//   {
//     requestId: "#10109097",
//     name: "Lara George",
//     email: "lara.george@icloud.com",
//     propertyAddress: "88 Victoria Island",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 815 456 7890",
//     landlordAgentNumber: "+234 809 123 4560",
//     propertyType: "Condo",
//     linkToProperty: "www.realestate.ng/victoria-condo",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "Lara George",
//   },
//   {
//     requestId: "#10109098",
//     name: "John Oboh",
//     email: "john.oboh@hotmail.com",
//     propertyAddress: "1 Benin Avenue",
//     assignedAgent: "Unassigned",
//     status: "Pending",
//     phoneNumber: "+234 810 123 4567",
//     landlordAgentNumber: "+234 809 876 5433",
//     propertyType: "Duplex",
//     linkToProperty: "www.tivro.africca/benin-duplex",
//     createdAt: "14 Aug 2024, 02:47 PM",
//     address: "14, kayode Alabi street",
//     requesterName: "John Oboh",
//   },
// ];
