// TaskData.ts

import { TaskData, TaskSummaryDataType } from "./TaskDataType";

export const tasksummaryData: TaskSummaryDataType = {
  summary: {
    totalRequest: 120,
    CompletedVerification: 60,
    failedVerification: 20,
    ongoingVerification: 40,
  },
};

export const tasks: TaskData[] = [
  // {
  //   id: 348001,
  //   landlord_name: "Olivia Smith",
  //   tenantName: "Daniel Johnson",
  //   tenantEmail: "daniel.j@example.com",
  //   tenantContact: "+2348123456789",
  //   gender: "Male",
  //   dateRequested: "01 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Passed",
  //   completedAt: "03 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Passed",
  //       lineManagerCheck: "Passed",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [{ name: "Proof of ID", url: "/uploads/id-daniel.pdf" }],
  //     },
  //   },
  // },
  // {
  //   requestId: "748002",
  //   landlordName: "Ibrahim Yusuf",
  //   tenantName: "Adaora Nwosu",
  //   tenantEmail: "adaora.n@example.com",
  //   tenantContact: "+2348031122334",
  //   gender: "Female",
  //   dateRequested: "02 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Ongoing",
  //   completedAt: "04 Jun 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Pending",
  //     employmentCheck: {
  //       status: "Pending",
  //       lineManagerCheck: "Pending",
  //       idAndIncomeCheck: "Pending",
  //       uploads: [{ name: "Utility Bill", url: "/uploads/bill-adaora.pdf" }],
  //     },
  //   },
  // },
  // {
  //   requestId: "657003",
  //   landlordName: "Esther Bello",
  //   tenantName: "Chinedu Okafor",
  //   tenantEmail: "chinedu.o@example.com",
  //   tenantContact: "+2347067788990",
  //   gender: "Male",
  //   dateRequested: "03 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Failed",
  //   completedAt: "05 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Failed",
  //     creditCheck: "Failed",
  //     employmentCheck: {
  //       status: "Failed",
  //       lineManagerCheck: "Failed",
  //       idAndIncomeCheck: "Failed",
  //       uploads: [{ name: "National ID", url: "/uploads/id-chinedu.pdf" }],
  //     },
  //   },
  // },
  // {
  //   requestId: "849004",
  //   landlordName: "Grace Adeniran",
  //   tenantName: "Blessing Umeh",
  //   tenantEmail: "blessing.u@example.com",
  //   tenantContact: "+2348054433221",
  //   gender: "Female",
  //   dateRequested: "04 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Ongoing",
  //   completedAt: "04 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Passed",
  //       lineManagerCheck: "Pending",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [
  //         { name: "Bank Statement", url: "/upload/statement-blessing.pdf" },
  //       ],
  //     },
  //   },
  // },
  // {
  //   requestId: "849005",
  //   landlordName: "Michael Obi",
  //   tenantName: "Sarah Aliyu",
  //   tenantEmail: "sarah.a@example.com",
  //   tenantContact: "+2348133344556",
  //   gender: "Female",
  //   dateRequested: "05 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Passed",
  //   completedAt: "06 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Passed",
  //       lineManagerCheck: "Passed",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [{ name: "Work ID", url: "/uploads/id-sarah.pdf" }],
  //     },
  //   },
  // },
  // {
  //   requestId: "934006",
  //   landlordName: "Tomi Rotimi",
  //   tenantName: "Samuel Bassey",
  //   tenantEmail: "samuel.b@example.com",
  //   tenantContact: "+2348101122334",
  //   gender: "Male",
  //   dateRequested: "06 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Pending",
  //   completedAt: "04 May 2024",
  //   verificationChecks: {
  //     identityCheck: "Pending",
  //     creditCheck: "Pending",
  //     employmentCheck: {
  //       status: "Pending",
  //       lineManagerCheck: "Pending",
  //       idAndIncomeCheck: "Pending",
  //       uploads: [
  //         { name: "Guarantor Form", url: "/uploads/guarantor-amaka.pdf" },
  //       ],
  //     },
  //   },
  // },
  // {
  //   requestId: "847007",
  //   landlordName: "Chuka Obi",
  //   tenantName: "Ngozi Eze",
  //   tenantEmail: "ngozi.e@example.com",
  //   tenantContact: "+2348145566778",
  //   gender: "Female",
  //   dateRequested: "07 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Failed",
  //   completedAt: "08 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Failed",
  //     employmentCheck: {
  //       status: "Failed",
  //       lineManagerCheck: "Passed",
  //       idAndIncomeCheck: "Failed",
  //       uploads: [{ name: "Pay Slip", url: "/uploads/pay-ngozi.pdf" }],
  //     },
  //   },
  // },
  // {
  //   requestId: "393008",
  //   landlordName: "Lola Dada",
  //   tenantName: "Femi Adebayo",
  //   tenantEmail: "femi.a@example.com",
  //   tenantContact: "+2348023344556",
  //   gender: "Male",
  //   dateRequested: "08 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Passed",
  //   completedAt: "09 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Passed",
  //       lineManagerCheck: "Passed",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [
  //         { name: "Work Reference", url: "/uploads/reference-femi.pdf" },
  //       ],
  //     },
  //   },
  // },
  // {
  //   requestId: "584009",
  //   landlordName: "Uche Nnaji",
  //   tenantName: "Tolu Ayeni",
  //   tenantEmail: "tolu.a@example.com",
  //   tenantContact: "+2348122299887",
  //   gender: "Male",
  //   dateRequested: "09 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Ongoing",
  //   completedAt: "22 Sep 2024",
  //   verificationChecks: {
  //     identityCheck: "Pending",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Failed",
  //       lineManagerCheck: "Pending",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [
  //         { name: "Guarantor Form", url: "/uploads/guarantor-amaka.pdf" },
  //       ],
  //     },
  //   },
  // },
  // {
  //   requestId: "459010",
  //   landlordName: "Jennifer Obi",
  //   tenantName: "Amaka Ike",
  //   tenantEmail: "amaka.i@example.com",
  //   tenantContact: "+2348065567788",
  //   gender: "Female",
  //   dateRequested: "10 Mar 2024",
  //   createdAt: "14 Aug 2024, 2:07 PM",
  //   status: "Passed",
  //   completedAt: "11 Mar 2024",
  //   verificationChecks: {
  //     identityCheck: "Passed",
  //     creditCheck: "Passed",
  //     employmentCheck: {
  //       status: "Passed",
  //       lineManagerCheck: "Passed",
  //       idAndIncomeCheck: "Passed",
  //       uploads: [
  //         { name: "Guarantor Form", url: "/uploads/guarantor-amaka.pdf" },
  //       ],
  //     },
  //   },
  // },
];
