import {
  LandlordDetailsType,
  LandlordSummaryDataType,
} from "./landlordDataType";

export const landlordDetails: LandlordDetailsType[] = [
  {
    id: 10169878,
    first_name: "Reginald",
    last_name: "Pepple",
    phone: "+234 916 014 0422",
    email: "reginaldabiepepple@gmail.com",
    status: "Active",
    dateCreated: "22 Sep 2025",
    createdAt: "14 Aug 2024, 2:47 PM",
    totalVerificationsSent: 100,
    totalPropertiesAdded: 10,
    totalTenantsAdded: 20,
    property_list: [
      {
        propertyName: "Palm Springs",
        maintenance: ["AC Repairs", "Window Fixes"],
        location: "Abeokuta",
        securityFeatures: "Fence, Local Vigilante",
        leaseTerms: "3-year lease",
        dateAdded: "20 Jul 2024, 10:00 AM",
        propertyType: "Bungalow",
        occupantsNumber: 2,
        createdAt: "20 Jul 2024, 10:00 AM",
        propertyDescription: "Quiet retreat bungalow on a hill.",
        occupants: [
          {
            fullName: "Kunle Adebayo",
            occupancyDate: "20 Jul 2024",
            renewalDate: "20 Jul 2027",
          },
          {
            fullName: "Titi Adebayo",
            occupancyDate: "20 Jul 2024",
            renewalDate: "20 Jul 2027",
          },
        ],
      },
      {
        propertyName: "Sunset Homes",
        maintenance: ["General Cleaning"],
        location: "Ilorin",
        securityFeatures: "CCTV",
        leaseTerms: "Yearly",
        dateAdded: "21 Jul 2024, 11:45 AM",
        propertyType: "Apartment",
        occupantsNumber: 1,
        createdAt: "21 Jul 2024, 11:45 AM",
        propertyDescription: "Simple apartments with power backup.",
        occupants: [
          {
            fullName: "Bashir Sule",
            occupancyDate: "21 Jul 2024",
            renewalDate: "21 Jul 2025",
          },
        ],
      },
      {
        propertyName: "Evergreen Lodge",
        maintenance: ["Fumigation"],
        location: "Owerri",
        securityFeatures: "Security Guard, Fence",
        leaseTerms: "2-year contract",
        dateAdded: "22 Jul 2024, 4:30 PM",
        propertyType: "Lodge",
        occupantsNumber: 3,
        createdAt: "22 Jul 2024, 4:30 PM",
        propertyDescription: "Student-friendly lodge near campus.",
        occupants: [
          {
            fullName: "Ngozi Eze",
            occupancyDate: "22 Jul 2024",
            renewalDate: "22 Jul 2026",
          },
          {
            fullName: "Obinna Ike",
            occupancyDate: "22 Jul 2024",
            renewalDate: "22 Jul 2026",
          },
          {
            fullName: "Zainab Musa",
            occupancyDate: "22 Jul 2024",
            renewalDate: "22 Jul 2026",
          },
        ],
      },
      {
        propertyName: "Jade Plaza",
        maintenance: ["Roof Fix", "Paint Work"],
        location: "Benin City",
        securityFeatures: "Electric Fence",
        leaseTerms: "5-year corporate",
        dateAdded: "23 Jul 2024, 9:00 AM",
        propertyType: "Commercial",
        occupantsNumber: 1,
        createdAt: "23 Jul 2024, 9:00 AM",
        propertyDescription: "Office spaces in a business district.",
        occupants: [
          {
            fullName: "GreenTech Ltd",
            occupancyDate: "23 Jul 2024",
            renewalDate: "23 Jul 2029",
          },
        ],
      },
      {
        propertyName: "Diamond Court",
        maintenance: ["Water System"],
        location: "Osogbo",
        securityFeatures: "Gate, Night Watch",
        leaseTerms: "1-year renewable",
        dateAdded: "24 Jul 2024, 3:20 PM",
        propertyType: "Flat",
        occupantsNumber: 2,
        createdAt: "24 Jul 2024, 3:20 PM",
        propertyDescription: "Compact housing with water tanks.",
        occupants: [
          {
            fullName: "Ayomide Balogun",
            occupancyDate: "24 Jul 2024",
            renewalDate: "24 Jul 2025",
          },
          {
            fullName: "Seyi Ayoola",
            occupancyDate: "24 Jul 2024",
            renewalDate: "24 Jul 2025",
          },
        ],
      },
      {
        propertyName: "Skyline Residence",
        maintenance: ["Elevator Servicing"],
        location: "Lekki Phase 1",
        securityFeatures: "CCTV, MOPOL",
        leaseTerms: "10-year luxury",
        dateAdded: "25 Jul 2024, 6:30 PM",
        propertyType: "Penthouse",
        occupantsNumber: 1,
        createdAt: "25 Jul 2024, 6:30 PM",
        propertyDescription: "Top-floor view with full luxury features.",
        occupants: [
          {
            fullName: "David Ikenna",
            occupancyDate: "25 Jul 2024",
            renewalDate: "25 Jul 2034",
          },
        ],
      },
    ],

    tenant_list: [
      {
        firstName: "Kunle",
        lastName: "Adebayo",
        phoneNumber: "+2348030000001",
        email: "kunle.adebayo@email.com",
        occupancyDate: "20 Jul 2024",
        renewalDate: "20 Jul 2027",
        propertyName: "Palm Springs",
        gender: "Male",
        status: "Active",
        createdAt: "20 Jul 2024",
        history: [],
      },
      {
        firstName: "Bashir",
        lastName: "Sule",
        phoneNumber: "+2348030000002",
        email: "bashir.sule@email.com",
        occupancyDate: "21 Jul 2024",
        renewalDate: "21 Jul 2025",
        propertyName: "Sunset Homes",
        gender: "Male",
        status: "Active",
        createdAt: "21 Jul 2024",
        history: [],
      },
      {
        firstName: "Ngozi",
        lastName: "Eze",
        phoneNumber: "+2348030000003",
        email: "ngozi.eze@email.com",
        occupancyDate: "22 Jul 2024",
        renewalDate: "22 Jul 2026",
        propertyName: "Evergreen Lodge",
        gender: "Female",
        status: "Active",
        createdAt: "22 Jul 2024",
        history: [],
      },
      {
        firstName: "Obinna",
        lastName: "Ike",
        phoneNumber: "+2348030000004",
        email: "obinna.ike@email.com",
        occupancyDate: "22 Jul 2024",
        renewalDate: "22 Jul 2026",
        propertyName: "Evergreen Lodge",
        gender: "Male",
        status: "Active",
        createdAt: "22 Jul 2024",
        history: [],
      },
      {
        firstName: "Ayomide",
        lastName: "Balogun",
        phoneNumber: "+2348030000005",
        email: "ayo.balogun@email.com",
        occupancyDate: "24 Jul 2024",
        renewalDate: "24 Jul 2025",
        propertyName: "Diamond Court",
        gender: "Male",
        status: "Active",
        createdAt: "24 Jul 2024",
        history: [],
      },
      {
        firstName: "David",
        lastName: "Ikenna",
        phoneNumber: "+2348030000006",
        email: "david.ikenna@email.com",
        occupancyDate: "25 Jul 2024",
        renewalDate: "25 Jul 2034",
        propertyName: "Skyline Residence",
        gender: "Male",
        status: "Active",
        createdAt: "25 Jul 2024",
        history: [],
      },
    ],

    verificationRequests: [
      {
        fullName: "Kunle Adebayo",
        address: "11 Palm Hill Road, Abeokuta",
        date: "20 Jul 2024",
      },
      {
        fullName: "Bashir Sule",
        address: "19 Harmony Avenue, Ilorin",
        date: "21 Jul 2024",
      },
      {
        fullName: "Ngozi Eze",
        address: "2 Federal Lodge, Owerri",
        date: "22 Jul 2024",
      },
      {
        fullName: "GreenTech Ltd",
        address: "101 Jade Plaza, Benin",
        date: "23 Jul 2024",
      },
      {
        fullName: "Ayomide Balogun",
        address: "7 Unity Close, Osogbo",
        date: "24 Jul 2024",
      },
      {
        fullName: "David Ikenna",
        address: "Penthouse, Skyline, Lekki",
        date: "25 Jul 2024",
      },
    ],
  },
];

export const landlordsummaryData: LandlordSummaryDataType = {
  summary: {
    totalInspectionsRequested: 80,
    totalCompleted: 50,
    totalPending: 30,
  },
};
