import {
  AgentRegSummary,
  AgentAccSummary,
  AgentDetailedInfo,
} from "./AgentDataTypes";

export const agentRegSummary: AgentRegSummary = {
  totalFunnel: 23866,
  totalPending: 2434,
  totalApproved: 19674,
  totalDeclined: 500,
};

export const agentAccSummary: AgentAccSummary = {
  totalAgents: 10000,
  totalActive: 7000,
  totalBlocked: 3000,
  totalSuspended: 1000,
};

export const agents: AgentDetailedInfo[] = [
  {
    registrationId: "#1019089",
    fullName: "Gbenga Sonoiki",
    emailAddress: "gbenga.sonoiki@gmail.com",
    phoneNumber: "+2348022222299",
    address: "14 Adamawa Street, PH, Nigeria",
    gender: "Male",
    state: "Lagos",
    lga: "Ikeja",
    city: "Lagos",
    propertyType: "Flat",
    jobCommitment: "Yes",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "14 Aug 2024, 02:47 PM",
    reviewerName: "Gbenga Sonoiki",
    status: "Failed",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019090",
    fullName: "Reginald Pepple",
    emailAddress: "reginaldabiepepple@gmail.com",
    phoneNumber: "+2349160140422",
    address: "14 Adamawa Street",
    gender: "Male",
    state: "Lagos",
    lga: "Ikeja",
    city: "Lagos",
    propertyType: "Duplex",
    jobCommitment: "Yes",
    flexibility: "Part-time",
    hasSmartphoneWithCamera: "No",
    createdAt: "14 Aug 2024, 02:47 PM",
    reviewerName: "Gbenga Sonoiki",
    status: "Active",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019091",
    fullName: "Amaka Obi",
    emailAddress: "amaka.obi@example.com",
    phoneNumber: "+2348051234567",
    address: "12 Marina Street",
    gender: "Female",
    state: "Lagos",
    lga: "Surulere",
    city: "Lagos",
    propertyType: "Self-Contain",
    jobCommitment: "No",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "12 Aug 2024, 10:00 AM",
    reviewerName: "Chinedu Okoro",
    status: "Active",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019092",
    fullName: "Tunde Bakare",
    emailAddress: "tunde.bakare@example.com",
    phoneNumber: "+2348034445566",
    address: "22 Kingsway Road",
    gender: "Male",
    state: "Lagos",
    lga: "Lekki",
    city: "Lagos",
    propertyType: "Bungalow",
    jobCommitment: "No",
    flexibility: "Part-time",
    hasSmartphoneWithCamera: "No",
    createdAt: "10 Aug 2024, 11:30 AM",
    reviewerName: "Ngozi Umeh",
    status: "Blocked",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019093",
    fullName: "Uche Eze",
    emailAddress: "uche.eze@example.com",
    phoneNumber: "+2348021112233",
    address: "5 Allen Avenue",
    gender: "Male",
    state: "Lagos",
    lga: "Ikeja",
    city: "Lagos",
    propertyType: "Bungalow",
    jobCommitment: "Yes",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "No",
    createdAt: "09 Aug 2024, 09:45 AM",
    reviewerName: "Gbenga Sonoiki",
    status: "Suspended",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019094",
    fullName: "Kemi Balogun",
    emailAddress: "kemi.balogun@example.com",
    phoneNumber: "+2348139876543",
    address: "18 Opebi Road",
    gender: "Female",
    state: "Lagos",
    lga: "Yaba",
    city: "Lagos",
    propertyType: "Flat",
    jobCommitment: "No",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "08 Aug 2024, 04:20 PM",
    reviewerName: "Tola Adebayo",
    status: "Active",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019095",
    fullName: "Ayo Bello",
    emailAddress: "ayo.bello@example.com",
    phoneNumber: "+2348145556677",
    address: "1 Awolowo Way",
    gender: "Male",
    state: "Lagos",
    lga: "Ikeja",
    city: "Lagos",
    propertyType: "Duplex",
    jobCommitment: "Yes",
    flexibility: "Part-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "07 Aug 2024, 01:15 PM",
    reviewerName: "Ngozi Umeh",
    status: "Blocked",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019096",
    fullName: "Chinyere Nnaji",
    emailAddress: "chinyere.nnaji@example.com",
    phoneNumber: "+2349091122334",
    address: "7 Ikorodu Road",
    gender: "Female",
    state: "Lagos",
    lga: "Ikorodu",
    city: "Lagos",
    propertyType: "Duplex",
    jobCommitment: "No",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "06 Aug 2024, 03:50 PM",
    reviewerName: "Chinedu Okoro",
    status: "Active",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019097",
    fullName: "John Paul",
    emailAddress: "john.paul@example.com",
    phoneNumber: "+2348067778899",
    address: "20 Ajao Estate",
    gender: "Male",
    state: "Lagos",
    lga: "Surulere",
    city: "Lagos",
    propertyType: "Bungalow",
    jobCommitment: "Yes",
    flexibility: "Full-time",
    hasSmartphoneWithCamera: "Yes",
    createdAt: "05 Aug 2024, 02:00 PM",
    reviewerName: "Tola Adebayo",
    status: "Suspended",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
  {
    registrationId: "#1019098",
    fullName: "Bola Shonubi",
    emailAddress: "bola.shonubi@example.com",
    phoneNumber: "+2348189990001",
    address: "15 Freedom Way",
    gender: "Female",
    state: "Lagos",
    lga: "Ajah",
    city: "Lagos",
    propertyType: "Flat",
    jobCommitment: "No",
    flexibility: "Part-time",
    hasSmartphoneWithCamera: "No",
    createdAt: "04 Aug 2024, 09:00 AM",
    reviewerName: "Gbenga Sonoiki",
    status: "Active",
    activities: [
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Completed",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
      {
        date: "14 Aug 2024, 3:34 PM",
        location: "14, Kayode Alabi Street",
        status: "Pending",
      },
    ],
  },
];
